elasticsearch:
  elasticsearch.additional.nodes:
  - localhost:9300
  - localhost:9300

  elasticsearch.cluster: ${ELASTIC_SEARCH_CLUSTER:-elasticsearch}
  elasticsearch.alias: ${ELASTIC_SEARCH_AUDIT_EVENTS_ALIAS:-auditevents}
  elasticsearch.doctype: ${ELASTIC_SEARCH_AUDIT_EVENT_DOCTYPE:-auditevent}
  elasticsearch.host: ${ELASTIC_SEARCH_HOST:-localhost}
  elasticsearch.port: ${ELASTIC_SEARCH_PORT:-9300}
  #
  elasticsearch.xpack.user: ${ELASTIC_SEARCH_XPACK_USER:-elastic}
  elasticsearch.xpack.password: ${ELASTIC_SEARCH_XPACK_PASSWORD:-changeme}

multiThread:
  batchSize: 10
  elasticSearchBulkSize: 10
  readerThreadsCount: 10

nsDataSourceFactory:
  properties:
    hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate.connection.driver_class: org.postgresql.Driver
    hibernate.show_sql: false
    hibernate.format_sql: false
    hibernate.use_sql_comments: false
    hibernate.connection.username: ${DB_NS_USER:-postgres_data}
    hibernate.connection.password: ${DB_NS_PASSWORD:-postgres_data}
    hibernate.connection.url: ${DB_NS_JDBC_URL:-jdbc:postgresql://127.0.0.1:5432/postgres_data}
    hibernate.default_schema: ${DB_NS_DEFAULT_SCHEMA:-perry}
    hibernate.connection.connectionTimeout: 1000000
    hibernate.connection.loginTimeout: 1000000
    hibernate.connection.keepAliveTimeOut: 8
    hibernate.jdbc.time_zone: America/Los_Angeles
    hibernate.jdbc.use_scrollable_resultset: true
    hibernate.id.new_generator_mappings: false
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate.cache.use_query_cache: true
    hibernate.connection.autocommit: false
    hibernate.connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    hibernate.hikari.minimumIdle: 4
    hibernate.hikari.maximumPoolSize: 10
    hibernate.hikari.maxLifetime: 900000
    hibernate.hikari.idleTimeout: 90000
    hibernate.hikari.connectionTimeout: 45000
    hibernate.hikari.registerMbeans: true
